### Site Settings ###
title               : Somansh
description         : >-
                      Knowledge builds up. Like compound interest.
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : somanshreddy/somanshreddy.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : true                            # Opens external URLs in new tab (works for posts, projects and navbar only)
url                 : https://somanshreddy.github.io/

### Plugins ###
plugins:
  - jemoji
  - jekyll-sitemap


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - pages/projects.html


### Author Info ###
author:
  name              : Somansh
  image             : somansh.jpeg
# behance           : your_username
# dribbble          : your_username
  email             : somanshreddy@gmail.com
  # facebook          : your_username
  github            : somanshreddy
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : somansh-reddy-satish-7a73a5169
  # medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : ASomansh
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title
future: true


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:                                             # For Documentation Only
    output: true                                        # For Documentation Only


### Disqus ###
disqus:
  shortname: somanshreddy                 # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: true                                        # Set true to enable analytics
  google:
    tracking_id: G-WSGF54W9LX


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
